import { db } from '@/db';
import { orders } from '@/db/schema';

async function main() {
    const sampleOrders = [
        {
            customerName: 'Alice Johnson',
            customerEmail: 'alice.johnson@example.com',
            customerPhone: '555-123-4567',
            shippingAddress: '123 Maple St, Anytown, CA 90210',
            totalAmount: 185.75,
            status: 'delivered',
            createdAt: new Date('2024-01-05T10:30:00Z').toISOString(),
        },
        {
            customerName: 'Bob Williams',
            customerEmail: 'bob.williams@example.com',
            customerPhone: '(555) 987-6543',
            shippingAddress: '456 Oak Ave, Villagetown, NY 10001',
            totalAmount: 349.99,
            status: 'shipped',
            createdAt: new Date('2024-01-07T14:00:00Z').toISOString(),
        },
        {
            customerName: 'Charlie Brown',
            customerEmail: 'charlie.b@example.com',
            customerPhone: '555 234 5678',
            shippingAddress: '789 Pine Dr, Cityville, TX 77001',
            totalAmount: 75.50,
            status: 'processing',
            createdAt: new Date('2024-01-10T09:15:00Z').toISOString(),
        },
        {
            customerName: 'Diana Prince',
            customerEmail: 'd.prince@example.com',
            customerPhone: '+1-555-876-5432',
            shippingAddress: '101 Main Rd, Hometown, FL 33101',
            totalAmount: 50.00,
            status: 'pending',
            createdAt: new Date('2024-01-12T11:45:00Z').toISOString(),
        },
        {
            customerName: 'Eve Davis',
            customerEmail: 'eve.d@example.com',
            customerPhone: '5551112233',
            shippingAddress: '202 Bridge Ln, Metropol, GA 30303',
            totalAmount: 230.25,
            status: 'delivered',
            createdAt: new Date('2024-01-15T16:20:00Z').toISOString(),
        },
        {
            customerName: 'Frank Miller',
            customerEmail: 'frank.m@example.com',
            customerPhone: '555-444-5555',
            shippingAddress: '303 River St, Suburbia, WA 98101',
            totalAmount: 410.00,
            status: 'shipped',
            createdAt: new Date('2024-01-18T08:00:00Z').toISOString(),
        },
        {
            customerName: 'Grace Lee',
            customerEmail: 'grace.lee@example.com',
            customerPhone: '(555) 777-8899',
            shippingAddress: '404 Hilltop Gdns, Uplands, CO 80010',
            totalAmount: 95.00,
            status: 'processing',
            createdAt: new Date('2024-01-20T13:00:00Z').toISOString(),
        },
        {
            customerName: 'Henry Wilson',
            customerEmail: 'henry.w@example.com',
            customerPhone: '555 666 0000',
            shippingAddress: '505 Ocean Dr, Coastal Town, OR 97201',
            totalAmount: 120.40,
            status: 'pending',
            createdAt: new Date('2024-01-22T10:10:00Z').toISOString(),
        },
        {
            customerName: 'Ivy Chen',
            customerEmail: 'ivy.c@example.com',
            customerPhone: '+1.555.222.3333',
            shippingAddress: '606 Park Blvd, Greenscape, NC 27511',
            totalAmount: 18.99,
            status: 'delivered',
            createdAt: new Date('2024-01-25T15:00:00Z').toISOString(),
        },
        {
            customerName: 'Jack Taylor',
            customerEmail: 'jack.t@example.com',
            customerPhone: '555-999-1111',
            shippingAddress: '707 Forest Rd, Woodland, AZ 85001',
            totalAmount: 380.50,
            status: 'shipped',
            createdAt: new Date('2024-01-28T09:30:00Z').toISOString(),
        },
        {
            customerName: 'Karen White',
            customerEmail: 'karen.w@example.com',
            customerPhone: '555-333-4444',
            shippingAddress: '808 Lake View, Serenity, NV 89101',
            totalAmount: 65.20,
            status: 'processing',
            createdAt: new Date('2024-02-01T11:00:00Z').toISOString(),
        },
        {
            customerName: 'Liam Green',
            customerEmail: 'liam.g@example.com',
            customerPhone: '(555) 000-1122',
            shippingAddress: '909 Summit Pkwy, Peakville, UT 84101',
            totalAmount: 299.00,
            status: 'pending',
            createdAt: new Date('2024-02-03T14:00:00Z').toISOString(),
        },
        {
            customerName: 'Mia Hall',
            customerEmail: 'mia.h@example.com',
            customerPhone: '555 777 9999',
            shippingAddress: '111 Country Ln, Farmland, KS 66001',
            totalAmount: 45.75,
            status: 'delivered',
            createdAt: new Date('2024-02-05T10:40:00Z').toISOString(),
        },
        {
            customerName: 'Noah King',
            customerEmail: 'noah.k@example.com',
            customerPhone: '+1-555-666-7777',
            shippingAddress: '222 City Center Blvd, Downtown, IL 60601',
            totalAmount: 155.00,
            status: 'shipped',
            createdAt: new Date('2024-02-08T12:00:00Z').toISOString(),
        },
        {
            customerName: 'Olivia Scott',
            customerEmail: 'olivia.s@example.com',
            customerPhone: '555-123-9876',
            shippingAddress: '333 Industrial Rd, Innovate, PA 19101',
            totalAmount: 270.30,
            status: 'processing',
            createdAt: new Date('2024-02-10T09:00:00Z').toISOString(),
        },
        {
            customerName: 'Peter Adams',
            customerEmail: 'peter.a@example.com',
            customerPhone: '555 456 7890',
            shippingAddress: '444 Academic Way, University, MA 02138',
            totalAmount: 88.00,
            status: 'pending',
            createdAt: new Date('2024-02-12T16:00:00Z').toISOString(),
        },
        {
            customerName: 'Quinn Baker',
            customerEmail: 'quinn.b@example.com',
            customerPhone: '(555) 789-0123',
            shippingAddress: '555 Quiet Village, Retreat, VT 05602',
            totalAmount: 35.50,
            status: 'delivered',
            createdAt: new Date('2024-02-15T11:20:00Z').toISOString(),
        },
        {
            customerName: 'Rachel Turner',
            customerEmail: 'rachel.t@example.com',
            customerPhone: '5559998877',
            shippingAddress: '666 Ocean View Apt, Paradise, CA 90291',
            totalAmount: 430.75,
            status: 'shipped',
            createdAt: new Date('2024-02-18T13:45:00Z').toISOString(),
        },
        {
            customerName: 'Sam Carter',
            customerEmail: 'sam.c@example.com',
            customerPhone: '555-222-3333',
            shippingAddress: '777 North St, Polaris, ND 58103',
            totalAmount: 110.00,
            status: 'processing',
            createdAt: new Date('2024-02-20T08:30:00Z').toISOString(),
        },
        {
            customerName: 'Tina Rogers',
            customerEmail: 'tina.r@example.com',
            customerPhone: '+1 555 333 4444',
            shippingAddress: '888 Golden Ave, Sunnyvale, SC 29201',
            totalAmount: 60.00,
            status: 'pending',
            createdAt: new Date('2024-02-22T10:00:00Z').toISOString(),
        },
        {
            customerName: 'Ursula Bell',
            customerEmail: 'ursula.b@example.com',
            customerPhone: '555-123-0000',
            shippingAddress: '999 Sky High Tower, Cloud City, WA 98119',
            totalAmount: 215.99,
            status: 'shipped',
            createdAt: new Date('2024-02-25T15:10:00Z').toISOString(),
        },
        {
            customerName: 'Victor Wong',
            customerEmail: 'victor.w@example.com',
            customerPhone: '(555) 555-5555',
            shippingAddress: '1000 Green St, Eco Park, OR 97205',
            totalAmount: 320.50,
            status: 'delivered',
            createdAt: new Date('2024-02-28T09:00:00Z').toISOString(),
        },
        {
            customerName: 'Wendy Kim',
            customerEmail: 'wendy.k@example.com',
            customerPhone: '555 888 9999',
            shippingAddress: '111 Peach Ln, Orchard, GA 30308',
            totalAmount: 440.00,
            status: 'shipped',
            createdAt: new Date('2024-03-01T14:30:00Z').toISOString(),
        },
        {
            customerName: 'Xavier Young',
            customerEmail: 'xavier.y@example.com',
            customerPhone: '555-777-6666',
            shippingAddress: '222 Main St, Old Town, VA 22201',
            totalAmount: 90.00,
            status: 'cancelled',
            createdAt: new Date('2024-03-03T11:00:00Z').toISOString(),
        },
        {
            customerName: 'Yara Zuniga',
            customerEmail: 'yara.z@example.com',
            customerPhone: '+1 (555) 444-3333',
            shippingAddress: '333 Gold Way, Fortune, CA 95001',
            totalAmount: 165.25,
            status: 'processing',
            createdAt: new Date('2024-03-05T10:00:00Z').toISOString(),
        },
        {
            customerName: 'Grace Lee',
            customerEmail: 'grace.lee@example.com',
            customerPhone: '(555) 777-8899',
            shippingAddress: '404 Hilltop Gdns, Uplands, CO 80010',
            totalAmount: 125.00,
            status: 'shipped',
            createdAt: new Date('2024-02-09T13:00:00Z').toISOString(),
        },
        {
            customerName: 'Alice Johnson',
            customerEmail: 'alice.johnson@example.com',
            customerPhone: '555-123-4567',
            shippingAddress: '123 Maple St, Anytown, CA 90210',
            totalAmount: 60.10,
            status: 'pending',
            createdAt: new Date('2024-03-07T09:45:00Z').toISOString(),
        },
    ];

    await db.insert(orders).values(sampleOrders);

    console.log('✅ Orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});